### ISSUE TITLE
`solve_feautrier_order_2_uv` returns wrong v’s while u’s are fine.

### ISSUE THREAD

**Issue by FredDeCeuster** [Magritte-code/Magritte#168]
The resulting v’s from the `solve_feautrier_order_2_uv` seem wrong.
These values also don’t seem to be tested anywhere.
Probably best to remove or disable this solver.

**Comment by ThomasCeulemans** [comment]
I see at least a single error in the uv solver: 
At line 2007 in `solver.tpp`: 
`Sv[last] = two * inverse_dtau_l * (I_bdy_l - term_n);` (some boundary value thing for v) is defined, but never used (I would expect it to be used in line 2010, but there the value is just overwritten).
`Sv[last] = (A[last] * Sv[last-1]           ) * (one + FF[last-1]) * denominator;`

**Comment by ThomasCeulemans** [comment]
From some preliminary testing (using the `all_constant_single_ray.py` benchmark), the total range of values returned seems fine-ish, but they seem to be offset. This might indicate some issues to exist with the boundary conditions.
Edit: never mind, only the v for the first point on the ray is correct.
