### ISSUE TITLE
Magritte Anaconda environment

### ISSUE THREAD

**Issue by FredDeCeuster** [Magritte-code/Magritte#45]
If [Anaconda](https://www.anaconda.com/blog/individual-edition-2020-11) is properly installed, the `magritte` conda environment can be installed form the environment file, named `conda_env.yml`, which can be found [here](https://github.com/Magritte-code/Magritte/blob/stable/dependencies/conda_env.yml). To download it, run:
```
wget https://github.com/Magritte-code/Magritte/raw/stable/dependencies/conda_env.yml
```
Now `conda` can be used to create an environment from this file by running:
```
conda env create -f conda_env.yml
```
More information about the Magritte installation process can be found [here](https://magritte.readthedocs.io/en/stable/0_getting_started/0_quickstart.html).

**Comment by ThomasCeulemans** [comment]
This is not an issue. The documentation at [readthedocs](https://magritte.readthedocs.io) contains the installation procedure.
