### ISSUE TITLE
JOSS Review (Documentation and Examples)

### ISSUE THREAD

**Issue by CFGrote** [Magritte-code/Magritte#56]
# Documentation
## README
I'd add a bit more information to the README.md regarding the field(s) of research in which Magritte can be applied. Is it limited to the astrophysical domain or more broadly applicable (e.g. plasma physics).

## API docs
Rudimentary. Only very few cpp and no py objects are documented.
- [x] ~Add API documentation for the classes and functions exposed to the user.~
**Edit**: Same comment as made by @gonsie over at https://github.com/openjournals/joss-reviews/issues/3905#issuecomment-996978642.

## Community guidelines
- [x] Add guidelines for contributors (e.g. point to issue labels, recomment on forking vs. becoming a  repo member etc)

# Examples
## docs/src/1_examples/0_creating_models/0_create_analytic_disk.ipynb
- [x] Typo in cell [1]: "We create a Magritte model ~form~ from..."
- [x] Function `turbulence(rr)`: `rr` is not used in the function body
- [x] wdir issue: I modified cell [3] to 
```
wdir = os.path.abspath(os.path.join(os.getcwd(), 'Analytic_disk'))
```
Cell [6] then produces filenames such as "Analytic_diskco.txt" (without the "/" dir separator). I suggest to make use of `os.path.join()` to
construct paths (here and everywhere else in the code if applicable).

- [x] Error in cell [15]:
```
%%capture
mesher.convert_msh_to_pos (f'{bmesh_name}.msh', replace=True)
Error   : Unknown number option 'General.NativeFileChooser'
Error   : Unknown entity 1 of dimension 0
Error   : Could not read vertices
Error   : Error loading '/home/grotec/Repositories/JOSSReviews/Magritte/docs/src/1_examples/0_creating_models/Analytic_disk/analytic_disk.msh'
Error   : '/home/grotec/Repositories/JOSSReviews/Magritte/docs/src/1_examples/0_creating_models/Analytic_disk/analytic_disk_convert_to_pos.geo', line 2 : Unknown view 0
```

## 1_create_analytic_spiral.ipynb
- [x] Same typo as above
- [x] Same path issue as above
- [x] Error:
```
mesher.convert_msh_to_pos (f'{bmesh_name}.msh', replace=True)
Error   : Unknown number option 'General.NativeFileChooser'
Error   : Unknown entity 1 of dimension 0
Error   : Could not read vertices
Error   : Error loading '/home/grotec/Repositories/JOSSReviews/Magritte/docs/src/1_examples/0_creating_models/Analytic_spiral/analytic_spiral.msh'
Error   : '/home/grotec/Repositories/JOSSReviews/Magritte/docs/src/1_examples/0_creating_models/Analytic_spiral/analytic_spiral_convert_to_pos.geo', line 2 : Unknown view 0
```

I'll be happy to test the other examples but this should probably be sorted out first. Maybe worth a separate issue.

**Comment by FredDeCeuster** [comment]
Dear @CFGrote, many thanks for your comments!
I have tried to address most of these issues in the latest commit.
However, we are currently still working on the API documentation.

Some further comments:
- The `turbulence` function does indeed not use `rr`. However, since it is in general a function of `rr`, it seemed appropriate to include it here. That way, only the function body needs to be altered to change the turbulence, and not also cell [16] for instance.
- I prefer not to use `os.getcwd()` to keep the model files out of the source code. (The `os.path.join` suggestion was very helpful, thanks!).

And a question:
- I suspect that the error might have something to do with the file names. Could you show me the content of the model directory `'/home/grotec/Repositories/JOSSReviews/Magritte/docs/src/1_examples/0_creating_models/Analytic_disk`?

**Comment by CFGrote** [comment]
>     * I suspect that the error might have something to do with the file names. Could you show me the content of the model directory `'/home/grotec/Repositories/JOSSReviews/Magritte/docs/src/1_examples/0_creating_models/Analytic_disk`?

See attached and 

![image](https://user-images.githubusercontent.com/15476807/146559940-383be15f-8751-466e-a5cb-50530b2962b8.png)

. Thanks for looking into this.
[co.txt](https://github.com/Magritte-code/Magritte/files/7735747/co.txt)

**Comment by FredDeCeuster** [comment]
Thanks!
So no mesh files seem to have been created.
Since I presume you also made alterations to the notebook, could you send me the entire notebook please?

**Comment by CFGrote** [comment]
in my fork at [docs/src/1_examples/0_creating_models/0_create_analytic_disk.ipynb](https://github.com/mpievolbio-scicomp/Magritte/blob/stable/docs/src/1_examples/0_creating_models/0_create_analytic_disk.ipynb)

**Comment by FredDeCeuster** [comment]
Interesting... That works for me with a fresh install...

Could you comment out the `%%capture` in the cells above please?
And in cell [15] change `replace=True` to `replace=False`?
That should give us more info as to what is happening...
Cell [14] should create a .msh file in the directory `wdir`.
This normally gets replaced in cell [15], unless you specify `replace=False`.
So now it should still be there. Could you also send me that file?

Perhaps relevant, how did you install `gmsh`?

Many thanks!

**Comment by CFGrote** [comment]
I tried again with `%%capture` magics removed. This time the notebook runs through to the end. Not sure what caused the earlier errors.

I installed gmsh via apt package manager (debian 10.2).

**Comment by CFGrote** [comment]
> Dear @CFGrote, many thanks for your comments! I have tried to address most of these issues in the latest commit. However, we are currently still working on the API documentation.
> 
> Some further comments:
> 
>     * The `turbulence` function does indeed not use `rr`. However, since it is in general a function of `rr`, it seemed appropriate to include it here. That way, only the function body needs to be altered to change the turbulence, and not also cell [16] for instance.
> 
>     * I prefer not to use `os.getcwd()` to keep the model files out of the source code. (The `os.path.join` suggestion was very helpful, thanks!).
> 
> 
> And a question:
> 
>     * I suspect that the error might have something to do with the file names. Could you show me the content of the model directory `'/home/grotec/Repositories/JOSSReviews/Magritte/docs/src/1_examples/0_creating_models/Analytic_disk`?

ok, sounds reasonable to me. thanks for clarifying!
