### ISSUE TITLE
Missing details on analytics benchmark

### ISSUE THREAD

**Issue by gonsie** [Magritte-code/Magritte#61]
This page is currently empty.
https://magritte.readthedocs.io/en/stable/2_benchmarks/0_analytic_benchmarks.html

This is related to the review in openjournals/joss-reviews#3905

**Comment by FredDeCeuster** [comment]
Dear @gonsie, thanks for your issue report!
I've added some more details on the analytic benchmark page.
Let me know if I can provide any further information.

**Comment by gonsie** [comment]
Thank you, that helps.
